package com.zhuke.comlibrary.content;

/**
 * 请求接口
 */
public class RequestAction {
    public static final String ACTION_LOGIN = "/xgf/user/login";//登录
    public static final String ACTION_EXIT = "/xgf/user/exit";//退出登录
    public static final String ACTION_SHOPPING_CART = "/xgf/shopcart/myShopcart";//我的购物车
    public static final String ACTION_MODIFY_SHOPPING_CART = "/xgf/shopcart/change";//修改购物车数量
    public static final String ACTION_DELETE_SHOPPING_CART = "/xgf/shopcart/delete";//删除购物车
    public static final String ACTION_SUBMIT_ORDER = "/xgf/order/submitOrder";//提交订单
    public static final String ACTION_ADDRESS_LIST = "/xgf/address/addressList";//收货地址列表
    public static final String ACTION_SET_ADDRESS = "/xgf/address/setDefault";//设置默认收货地址
    public static final String ACTION_ADD_ADDRESS = "/xgf/address/add";//添加收货地址
    public static final String ACTION_ADD_SHOPING_CAR= "/xgf/shopcart/add";//添加购物车
    public static final String ACTION_SEND_CODE = "/xgf/user/sendVerify";//发送验证码
    public static final String ACTION_CHECK = "/xgf/user/checkVerify";//校验验证码
    public static final String ACTION_REGIST = "/xgf/user/register";//注册
    public static final String ACTION_LICENSE_PIC = "/xgf/store/licensePic";//上传营业执照
    public static final String ACTION_STORE_PIC = "/xgf/store/StorePic";//上传门店照
    public static final String ACTION_CONTRACT_PIC = "/xgf/store/contractPic";//上传房屋租赁合同
    public static final String ACTION_UTILITIES_PIC = "/xgf/store/utilitiesPic";//上传水电费
    public static final String ACTION_STORE_APPLY = "/xgf/store/apply";//商铺申请
    public static final String ACTION_STORE_COLLECTION = "/xgf/collection/collectionList";//收藏列表
    public static final String ACTION_STORE_REMOVE_COLLECTION = "/xgf/collection/cancel";//移除收藏列表
    public static final String ACTION_ADD_COLLECTION = "/xgf/collection/add";//添加收藏
    public static final String ACTION_SEARCHHISTORY = "/xgf/search/searchHistory";//历史记录
    public static final String ACTION_COMMODITY_CATEGORY = "/xgf/commodity/category";//左侧分类列表
    public static final String ACTION_COMMODITY_CATEGORYLIST = "/xgf/commodity/categoryList";//右侧分类数据
    public static final String ACTION_SEARCH_COMMODITY = "/xgf/search/searchCommodity";//右侧分类数据
    public static final String ACTION_EDIT_PWD = "xgf/user/editPwd";//修改密码
    public static final String ACTION_LOST_PWD = "xgf/user/lostPwd";//忘记密码
    public static final String ACTION_FACE = "xgf/face/getToken";//Face ++
    public static final String ACTION_STORE_QUERY = "/xgf/store/query";//查询商铺信息
    public static final String ACTION_USER_INFO = "/xgf/user/userInfo";//查询用户信息
    public static final String ACTION_USER_GETSTATUS = "/xgf/user/getStatus";//获取认证状态
    public static final String ACTION_GET_PREVIEWURL = "/xgf/bestsign/getPreviewURL";//获取合同预览
    public static final String ACTION_SIGN = "/xgf/bestsign/upImgAndSign";//签约
    public static final String ACTION_CLEAR_HISTORY = "/xgf/search/clearHistory";//清除历史记录
    public static final String ACTION_INTERNET_BANK = "/xgf/bank/internetBank";//网银认证
    public static final String ACTION_INTERNET_OPERATOR = "/xgf/cert/operator";//运营商认证
    public static final String ACTION_ADD_CONTACT = "xgf/user/addContact";//添加联系人
    public static final String ACTION_DICTIONARY_LIST = "/xgf/dictionary/list";//联系人关系数据字典
    public static final String ACTION_USER_HEAD = "/xgf/user/userHead";//修改用户头像
    public static final String ACTION_EDIT_PHONE = "/xgf/user/editPhone";//修改手机号
    public static final String ACTION_SELECTORDER = "/xgf/order/selectOrder";//所有订单
    public static final String ACTION_COMMODITYAD = "/xgf/home/commodityAd";//商品广告
    public static final String ACTION_EXHIBITION = "/xgf/home/exhibition";//横栏广告
    public static final String ACTION_COMMODITY_DETAIL = "/xgf/commodity/detail";//商品详情
    public static final String ACTION_FEEDBACK_LIST = "/xgf/feedBack/list";//帮助反馈列表
    public static final String ACTION_FEEDBACK_DETAILLIST = "xgf/feedBack/detailList";//帮助反馈详情列表
    public static final String ACTION_FEEDBACK_ADD = "xgf/feedBack/add";//添加反馈
    public static final String ACTION_REPAYLIST = "/xgf/repay/repayList";//还款计划
    public static final String ACTION_REPAYMENT = "/xgf/repay/repayment";//还款
    public static final String ACTION_BANKCARDLIST = "/xgf/repay/bankCardList";//银行卡列表
    public static final String ACTION_ADD_BANKCARD = "/xgf/repay/addBankCard";//添加银行卡
    public static final String ACTION_QUERYBALANCE = "xgf/user/queryBalance";//收入支出
    public static final String ACTION_CAROUSEL = "/xgf/home/carousel";//轮到图
    public static final String ACTION_CLICKNUM = "/xgf/home/clickNum";//轮到图点击
    public static final String ACTION_ADVERTISEMENT = "/xgf/home/advertisement";//消息通知
//    public static final String ACTION_CATEGORYLIST = "/xgf/home/categoryList";//首页精选类容
    public static final String ACTION_COMMODITYLIST = "/xgf/home/commodityList";//特色推荐(首页)
    public static final String ACTION_RECOMMENDLIST = "/xgf/home/recommendList";//特色推荐
    public static final String ACTION_LICENSE = "http://mrxiefresh.istarcredit.com/contract.html";
    public static final String ACTION_PAY = "/xgf/repay/queryMoney";//一键还款
    public static final String ACTION_BESTSIGN = "/xgf/bestsign/getContractsByUserId";//一键还款
    public static final String ACTION_BIND_BANK = "/xgf/third/reapalIdentify";//绑定银行卡
    public static final String ACTION_REPAY_USER = "/xgf/repay/userInfo";//获取用户银行卡信息
    public static final String ACTION_RESENDSMS = "/xgf/repay/reSendSms";//重新获取验证码
    public static final String ACTION_DOQUICKPAY = "/xgf/repay/doQuickPay";//正式还款
    public static final String ACTION_REPAY = "/xgf/repay/queryMoneys";//重新还款
    public static final String ACTION_ADDRESS_DELETE = "xgf/address/delete";//删除地址
    public static final String ACTION_ADDRESS_UPDATE = "/xgf/address/update";//修改地址
    public static final String ACTION_GENERATEORDER = "/xgf/order/generateOrder";//提交新订单
    public static final String ACTION_ORDERDETAIL = "/xgf/order/orderDetail";//订单详情
    public static final String ACTION_GETORDER = "/xgf/order/getOrder";//新订单查询
    public static final String ACTION_CANCELORDER = "/xgf/order/delete";//取消订单
    public static final String ACTION_AFFIRM = "/xgf/order/harvest";//确认收货
}
